name = "exdisdev"
version = "1.0.0"
target = "javascript"

[tools.lustre.bin]
bun = "system"

[tools.lustre.html]
stylesheets = [
  { href = "/style.css" }
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.1.3 and < 3.0.0"
